"use client";
// import type { Metadata } from "next";
// import Header from "./Header";
import { SidebarInset, SidebarProvider } from "@/components/ui/sidebar";
import { AppSidebar } from "./Sidebar";

// export const metadata: Metadata = {
//   title: "Uapp Chatbot",
//   description: "Generated by create next app",
// };

export default function PrivateLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className="h-screen flex flex-col ">
      <SidebarProvider
        className="flex flex-col flex-1 min-h-0"
        style={{ "--sidebar-width": "300px" } as React.CSSProperties}
      >
        <div className="flex flex-1 min-h-0">
          <AppSidebar />

          <SidebarInset className="bg-[#ecf0f0] px-4 py-2 flex-1 overflow-auto min-h-0 ">
            {children}
          </SidebarInset>
        </div>
      </SidebarProvider>
    </div>
  );
}
